---
name: tagged-release

on:
  push:
    tags:
      - "*"

jobs:
  tagged-release:
    name: Tagged Release
    runs-on: self-hosted
    steps:
      #- run: rm -fr $GITHUB_WORKSPACE && mkdir $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: true
      - run: |
          git submodule update --init --depth=1
          git submodule sync
      
      - name: Build
        run: |
          ./rk3568-config-photonicat-openwrt.sh
          export CROSS_COMPILE=aarch64-linux-gnu-
          ./build.sh

      - name: push image to release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            rockdev/pack/BOARDCONFIG-RK3568-PHOTONICAT-OPENWRT-DDR4-GPT-*.img
